server:
  port: 9090 

management:
  endpoint:
    gateway:
      enabled: true
    health:
      sensitive: false
    restart:
      enabled: true
    shutdown:
      enabled: true
    security:
    enabled: false
  
logging:
  level:
    org.springframework.cloud.consul: DEBUG

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
    consul:
      discovery:
        enabled: true
     